# Generated by Django 6.0 on 2026-02-26 07:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('brand', 'Brand'), ('influencer', 'Influencer')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('business_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('fashion', 'Fashion'), ('tech', 'Tech'), ('beauty', 'Beauty'), ('food', 'Food'), ('fitness', 'Fitness'), ('education', 'Education')], max_length=50)),
                ('description', models.TextField()),
                ('target_audience', models.CharField(max_length=255)),
                ('mission', models.TextField(blank=True, null=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=100, null=True)),
                ('usp', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('influencer_category', models.CharField(max_length=100)),
                ('preferred_platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter')], max_length=50)),
                ('follower_range', models.CharField(choices=[('1k-10k', '1K-10K (Nano)'), ('10k-50k', '10K-50K (Micro)'), ('50k-500k', '50K-500K (Macro)')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campaign_duration', models.CharField(max_length=100)),
                ('collaboration_type', models.CharField(choices=[('paid', 'Paid Promotion'), ('affiliate', 'Affiliate Marketing'), ('barter', 'Barter Collaboration'), ('giveaway', 'Giveaway Campaign'), ('ambassador', 'Brand Ambassador')], max_length=50)),
                ('deliverables', models.TextField(help_text='Example: 2 reels + 3 stories')),
                ('number_of_posts', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='app.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collabs', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campaign')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_collabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='influencer_profiles/')),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('niche', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('instagram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('youtube_channel_link', models.URLField(blank=True, null=True)),
                ('youtube_subscribers', models.PositiveIntegerField(default=0)),
                ('tiktok_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('engagement_rate', models.FloatField(blank=True, help_text='Enter percentage value', null=True)),
                ('average_views', models.PositiveIntegerField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('previous_collaborations', models.TextField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('media_kit', models.FileField(blank=True, null=True, upload_to='media_kits/')),
                ('languages_spoken', models.CharField(blank=True, max_length=200, null=True)),
                ('content_type', models.CharField(blank=True, choices=[('reels', 'Reels'), ('shorts', 'Shorts'), ('stories', 'Stories'), ('posts', 'Posts'), ('long_videos', 'Long Videos')], max_length=20, null=True)),
                ('price_per_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_post', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_story', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_details', models.TextField(blank=True, null=True)),
                ('negotiable', models.BooleanField(default=True)),
                ('audience_gender_percentage', models.CharField(blank=True, max_length=100, null=True)),
                ('audience_age_group', models.CharField(blank=True, max_length=100, null=True)),
                ('top_audience_country', models.CharField(blank=True, max_length=100, null=True)),
                ('audience_interests', models.TextField(blank=True, null=True)),
                ('available_for', models.CharField(blank=True, choices=[('paid_collab', 'Paid Collaborations'), ('affiliate', 'Affiliate Marketing'), ('reviews', 'Product Reviews'), ('events', 'Event Appearances')], max_length=20, null=True)),
                ('available_from', models.DateField(blank=True, null=True)),
                ('available_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
