# Generated by Django 5.1.6 on 2026-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
